'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sumar", ReplyAction:="*")>  _
        Function Sumar(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Sumar", ReplyAction:="*")>  _
        Function SumarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function Resta(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Resta", ReplyAction:="*")>  _
        Function RestaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function Multiplicacion(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Multiplicacion", ReplyAction:="*")>  _
        Function MultiplicacionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function Division(ByVal nro1 As Double, ByVal nro2 As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Division", ReplyAction:="*")>  _
        Function DivisionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fact", ReplyAction:="*")>  _
        Function Fact(ByVal n As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Fact", ReplyAction:="*")>  _
        Function FactAsync(ByVal n As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function Potencia(ByVal a As Integer, ByVal b As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Potencia", ReplyAction:="*")>  _
        Function PotenciaAsync(ByVal a As Integer, ByVal b As Integer) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function Seno(ByVal angulo As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Seno", ReplyAction:="*")>  _
        Function SenoAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function Tangente(ByVal angulo As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Tangente", ReplyAction:="*")>  _
        Function TangenteAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/inversa", ReplyAction:="*")>  _
        Function inversa(ByVal numero As Double) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/inversa", ReplyAction:="*")>  _
        Function inversaAsync(ByVal numero As Double) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/raiz_cuadrada", ReplyAction:="*")>  _
        Function raiz_cuadrada(ByVal numero As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/raiz_cuadrada", ReplyAction:="*")>  _
        Function raiz_cuadradaAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/raiz_n_esima", ReplyAction:="*")>  _
        Function raiz_n_esima(ByVal numero As Integer, ByVal raiz As Integer) As Double
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/raiz_n_esima", ReplyAction:="*")>  _
        Function raiz_n_esimaAsync(ByVal numero As Integer, ByVal raiz As Integer) As System.Threading.Tasks.Task(Of Double)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Sumar(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Sumar
            Return MyBase.Channel.Sumar(nro1, nro2)
        End Function
        
        Public Function SumarAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SumarAsync
            Return MyBase.Channel.SumarAsync(nro1, nro2)
        End Function
        
        Public Function Resta(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Resta
            Return MyBase.Channel.Resta(nro1, nro2)
        End Function
        
        Public Function RestaAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.RestaAsync
            Return MyBase.Channel.RestaAsync(nro1, nro2)
        End Function
        
        Public Function Multiplicacion(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Multiplicacion
            Return MyBase.Channel.Multiplicacion(nro1, nro2)
        End Function
        
        Public Function MultiplicacionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.MultiplicacionAsync
            Return MyBase.Channel.MultiplicacionAsync(nro1, nro2)
        End Function
        
        Public Function Division(ByVal nro1 As Double, ByVal nro2 As Double) As Double Implements ServiceReference1.WebService1Soap.Division
            Return MyBase.Channel.Division(nro1, nro2)
        End Function
        
        Public Function DivisionAsync(ByVal nro1 As Double, ByVal nro2 As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.DivisionAsync
            Return MyBase.Channel.DivisionAsync(nro1, nro2)
        End Function
        
        Public Function Fact(ByVal n As Integer) As Integer Implements ServiceReference1.WebService1Soap.Fact
            Return MyBase.Channel.Fact(n)
        End Function
        
        Public Function FactAsync(ByVal n As Integer) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReference1.WebService1Soap.FactAsync
            Return MyBase.Channel.FactAsync(n)
        End Function
        
        Public Function Potencia(ByVal a As Integer, ByVal b As Integer) As Integer Implements ServiceReference1.WebService1Soap.Potencia
            Return MyBase.Channel.Potencia(a, b)
        End Function
        
        Public Function PotenciaAsync(ByVal a As Integer, ByVal b As Integer) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReference1.WebService1Soap.PotenciaAsync
            Return MyBase.Channel.PotenciaAsync(a, b)
        End Function
        
        Public Function Seno(ByVal angulo As Double) As Double Implements ServiceReference1.WebService1Soap.Seno
            Return MyBase.Channel.Seno(angulo)
        End Function
        
        Public Function SenoAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.SenoAsync
            Return MyBase.Channel.SenoAsync(angulo)
        End Function
        
        Public Function Tangente(ByVal angulo As Double) As Double Implements ServiceReference1.WebService1Soap.Tangente
            Return MyBase.Channel.Tangente(angulo)
        End Function
        
        Public Function TangenteAsync(ByVal angulo As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.TangenteAsync
            Return MyBase.Channel.TangenteAsync(angulo)
        End Function
        
        Public Function inversa(ByVal numero As Double) As Double Implements ServiceReference1.WebService1Soap.inversa
            Return MyBase.Channel.inversa(numero)
        End Function
        
        Public Function inversaAsync(ByVal numero As Double) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.inversaAsync
            Return MyBase.Channel.inversaAsync(numero)
        End Function
        
        Public Function raiz_cuadrada(ByVal numero As Integer) As Double Implements ServiceReference1.WebService1Soap.raiz_cuadrada
            Return MyBase.Channel.raiz_cuadrada(numero)
        End Function
        
        Public Function raiz_cuadradaAsync(ByVal numero As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.raiz_cuadradaAsync
            Return MyBase.Channel.raiz_cuadradaAsync(numero)
        End Function
        
        Public Function raiz_n_esima(ByVal numero As Integer, ByVal raiz As Integer) As Double Implements ServiceReference1.WebService1Soap.raiz_n_esima
            Return MyBase.Channel.raiz_n_esima(numero, raiz)
        End Function
        
        Public Function raiz_n_esimaAsync(ByVal numero As Integer, ByVal raiz As Integer) As System.Threading.Tasks.Task(Of Double) Implements ServiceReference1.WebService1Soap.raiz_n_esimaAsync
            Return MyBase.Channel.raiz_n_esimaAsync(numero, raiz)
        End Function
    End Class
End Namespace
